on: [push, pull_request]


# For now only Linux wheels with Python 3.11. TODO: cover other Python
# versions and macOS / Windows.

jobs:
  build_wheels:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: Build wheels
    # The host system that runs Docker.
    runs-on: ${{ matrix.os }}
    # The Docker container the job is run in.
    container: ${{ matrix.os == 'ubuntu-latest' && 'quay.io/pypa/manylinux2014_x86_64' || null }}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: latest
          environment-file: ${{ matrix.os == 'ubuntu-latest' && 'ci/environment/conda-linux-64.lock' || 'ci/environment/conda-osx-64.lock' }}
      - name: Build the wheels
        # The following line here and elsewhere is needed for our Conda environment to
        # be activated. See:
        # https://github.com/marketplace/actions/setup-miniconda#important
        shell: bash -el {0}
        run: ci/build.sh
      - uses: actions/upload-artifact@v3
        with:
          path: "fixed-wheel/*.whl"
